### ISSUE TITLE
Illegal memory access when k=100  for Netflix dataset

### ISSUE THREAD

**Issue by isratnisa** [wei-tan/CuMF#13]
Hi,
Thanks for sharing the code. 
I am using a k80 machine. The code works fine for k=10,20,..40, but not anything more than 60. Did you ever encounter that problem?
[ss@gpu04 CuMF]$ ./main 70 .058 1 
F = 70, lambda = .058, THETA_BATCH = 1 
******_starting loading training and testing sets to host.
***_**_start allocating memory on GPU...
***_**_start copying memory to GPU...
CUDA Error:
File = als.cu
Line = 844
*_Reason = out of memory**
////////////////////////////////////////
[ss@gpu04 CuMF]$ ./main 100 .058 1 
F = 100, lambda = .058, THETA_BATCH = 1 
******_starting loading training and testing sets to host.
***_**_start allocating memory on GPU...
***_**_start copying memory to GPU...
*_CUDA failure als.cu:869: 'an illegal memory access was encountered'**

Thanks,
Israt

**Comment by wei-tan** [comment]
Hi when you increase F you should increase X and Theta batch. Here are some combinations we tried:
As you can see when F = 60, we used THETA_BATCH = 2.
Later when you try even larger F, X_BATCH and THETA_BATCH should both be increased.

#!/bin/bash
#$1 should be a directory
make clean build
mkdir $1
./main 17770 480189 10 99072112 1408395 0.048 1 1 ./data/netflix/ > $1/als.10
./main 17770 480189 20 99072112 1408395 0.048 1 1 ./data/netflix/ > $1/als.20
./main 17770 480189 30 99072112 1408395 0.048 1 1 ./data/netflix/ > $1/als.30

./main 17770 480189 40 99072112 1408395 0.048 1 2 ./data/netflix/ > $1/als.40
./main 17770 480189 50 99072112 1408395 0.048 1 2 ./data/netflix/ > $1/als.50
./main 17770 480189 60 99072112 1408395 0.048 1 2 ./data/netflix/ > $1/als.60

./main 17770 480189 70 99072112 1408395 0.048 1 3 ./data/netflix/ > $1/als.70
./main 17770 480189 80 99072112 1408395 0.048 1 3 ./data/netflix/ > $1/als.80
./main 17770 480189 90 99072112 1408395 0.048 1 3 ./data/netflix/ > $1/als.90
./main 17770 480189 100 99072112 1408395 0.048 1 3 ./data/netflix/ > $1/als.100

./main 17770 480189 110 99072112 1408395 0.048 1 4 ./data/netflix/ > $1/als.110
./main 17770 480189 120 99072112 1408395 0.048 1 4 ./data/netflix/ > $1/als.120

./main 17770 480189 130 99072112 1408395 0.048 1 10 ./data/netflix/ > $1/als.130
./main 17770 480189 140 99072112 1408395 0.048 1 10 ./data/netflix/ > $1/als.140
./main 17770 480189 150 99072112 1408395 0.048 1 10 ./data/netflix/ > $1/als.150
./main 17770 480189 160 99072112 1408395 0.048 1 10 ./data/netflix/ > $1/als.160
./main 17770 480189 170 99072112 1408395 0.048 1 10 ./data/netflix/ > $1/als.170
./main 17770 480189 180 99072112 1408395 0.048 1 10 ./data/netflix/ > $1/als.180
./main 17770 480189 190 99072112 1408395 0.048 1 10 ./data/netflix/ > $1/als.190
./main 17770 480189 200 99072112 1408395 0.048 1 10 ./data/netflix/ > $1/als.200

**Comment by isratnisa** [comment]
That solved the problem.
Thank you for your quick response.
